import * as github from "@actions/github";
import type { LintReport, RuleResult } from "@mdpact/core";

import type { ScoreBreakdown } from "./score.js";

const MARKER = "<!-- mdpact-report -->";

interface UpsertInput {
  report: LintReport;
  score: ScoreBreakdown;
  delta: { baseScore: number | null; ref: string };
  failBelow: number;
}

export async function upsertStickyComment(token: string, input: UpsertInput): Promise<void> {
  const { context } = github;
  const pr = context.payload.pull_request;
  if (!pr) return;

  const octokit = github.getOctokit(token);
  const body = renderBody(input);

  const { data: existing } = await octokit.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: pr.number,
    per_page: 100,
  });

  const mine = existing.find((c) => c.body?.includes(MARKER));

  if (mine) {
    await octokit.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: mine.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: pr.number,
      body,
    });
  }
}

function renderBody({ report, score, delta, failBelow }: UpsertInput): string {
  const lines: string[] = [];
  lines.push(MARKER);
  lines.push("");
  lines.push("## mdpact report");
  lines.push("");
  lines.push(renderScoreLine(score, delta, failBelow));
  lines.push("");
  lines.push(renderSeveritySummary(report));

  if (report.results.length > 0) {
    lines.push("");
    lines.push(renderViolations(report));
  }

  lines.push("");
  lines.push(
    "> Generated by [mdpact](https://github.com/HMAKT99/Agentspec). Thresholds and rules are configured in `mdpact.config.ts`.",
  );
  return lines.join("\n");
}

function renderScoreLine(
  score: ScoreBreakdown,
  delta: UpsertInput["delta"],
  failBelow: number,
): string {
  const emoji = score.total >= failBelow ? "🟢" : "🔴";
  const deltaText =
    delta.baseScore !== null
      ? ` (${formatDelta(score.total - delta.baseScore)} vs \`${delta.ref}\`)`
      : "";
  return `${emoji} **Score:** ${score.total}/100${deltaText} — threshold ${failBelow}`;
}

function formatDelta(n: number): string {
  if (n === 0) return "±0";
  return n > 0 ? `+${n}` : String(n);
}

function renderSeveritySummary(report: LintReport): string {
  const parts: string[] = [];
  if (report.errorCount > 0)
    parts.push(`🔴 ${report.errorCount} error${plural(report.errorCount)}`);
  if (report.warningCount > 0)
    parts.push(`🟡 ${report.warningCount} warning${plural(report.warningCount)}`);
  if (report.infoCount > 0) parts.push(`🔵 ${report.infoCount} info`);
  if (parts.length === 0) return "✅ No diagnostics.";
  return parts.join("  ·  ");
}

function renderViolations(report: LintReport): string {
  const byRule = new Map<string, RuleResult[]>();
  for (const r of report.results) {
    const arr = byRule.get(r.ruleId) ?? [];
    arr.push(r);
    byRule.set(r.ruleId, arr);
  }

  const out: string[] = ["<details>", "<summary>Diagnostics</summary>", ""];
  for (const [ruleId, results] of byRule) {
    out.push(`#### \`${ruleId}\`  (${results.length})`);
    for (const r of results) {
      out.push(`- \`${locOf(r)}\` — ${escapePipes(r.message)}`);
    }
    out.push("");
  }
  out.push("</details>");
  return out.join("\n");
}

function locOf(r: RuleResult): string {
  return `${r.range.start.file}:${r.range.start.line}:${r.range.start.column}`;
}

function plural(n: number): string {
  return n === 1 ? "" : "s";
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|");
}
